name: Build and Push LibreChat Image to GHCR

on:
  push:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 👇 Build using BOTH docker-compose.yml + docker-compose.override.yml
      - name: Build LibreChat images
        run: |
          docker compose -f docker-compose.yml -f docker-compose.override.yml build

      # 👇 Tag & push only the api service (LibreChat main service)
      - name: Tag and Push LibreChat API
        run: |
          IMAGE=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          echo "Pushing $IMAGE"
          docker tag librechat_api $IMAGE
          docker push $IMAGE
